--Ab hier kommen unkritische Datenbanken
USE [_DATABASE_]
GO
DBCC SHRINKFILE (N'_DATABASE__log' , 0, TRUNCATEONLY)
GO

--Ab hier kommen Speziel-Datenbanken
USE [master]
GO
ALTER DATABASE [_DATABASE_] SET RECOVERY SIMPLE WITH NO_WAIT
GO
USE [PDTransfer]
GO
DBCC SHRINKFILE (N'_DATABASE__log' , 0, TRUNCATEONLY)
GO
USE [master]
GO
ALTER DATABASE [_DATABASE_] SET RECOVERY FULL WITH NO_WAIT
GO